# Exceptions: try / catch / throw / $setcatch()

Dynamic Objects supports try / catch / throw like this: try /* Block of code for try */ catch {variable_name} /* Block of code if an exception is thrown */ end try The catch statement may optionally be followed by a variable name. In this case, the variable is updated with the exception object that is created when an exception is thrown. Simple exam  

**Created At:** 7/11/2019 12:56:51 PM  
**Updated At:** 7/16/2019 8:14:26 AM  

